<a href="https://colab.research.google.com/github/sonjoy1s/kaggle_project/blob/main/Diabetes_Risk_Prediction_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("/content/diabetes_risk_dataset.csv")
df.head()

,Patient_ID,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,1,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,2,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,3,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,4,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,5,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  6000 non-null   int64
 1   age                         6000 non-null   int64
 2   gender                      6000 non-null   object
 3   bmi                         6000 non-null   float64
 4   blood_pressure              6000 non-null   int64
 5   fasting_glucose_level       6000 non-null   int64
 6   insulin_level               6000 non-null   float64
 7   HbA1c_level                 6000 non-null   float64
 8   cholesterol_level           6000 non-null   int64
 9   triglycerides_level         6000 non-null   int64
 10  physical_activity_level     6000 non-null   object
 11  daily_calorie_intake        6000 non-null   int64
 12  sugar_intake_grams_per_day  6000 non-null   float64
 13  sleep_hours                 6000 non-null   float64
 14  stress_level                6000 non-null   int64
 15  family_history_diabetes     6000 non-null   object
 16  waist_circumference_cm      6000 non-null   float64
 17  diabetes_risk_score         6000 non-null   float64
 18  diabetes_risk_category      6000 non-null   object
dtypes: float64(7), int64(8), object(4)
memory usage: 890.8+ KB

In [15]:
df.columns

Index(['Patient_ID', 'age', 'gender', 'bmi', 'blood_pressure',
       'fasting_glucose_level', 'insulin_level', 'HbA1c_level',
       'cholesterol_level', 'triglycerides_level', 'physical_activity_level',
       'daily_calorie_intake', 'sugar_intake_grams_per_day', 'sleep_hours',
       'stress_level', 'family_history_diabetes', 'waist_circumference_cm',
       'diabetes_risk_score', 'diabetes_risk_category'],
      dtype='object')

In [16]:
df.drop(columns=['Patient_ID'], inplace=True)

In [17]:
df.head()

,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [18]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,6000.0,52.230667,18.757508,20.0,36.0,53.00,68.00,84.0
bmi,6000.0,32.939667,7.510155,16.0,26.9,32.75,38.50,50.0
blood_pressure,6000.0,144.482500,17.867248,91.0,132.0,144.00,157.00,200.0
fasting_glucose_level,6000.0,106.105500,31.213994,60.0,87.0,96.00,114.00,281.0
insulin_level,6000.0,15.080333,9.245581,2.0,7.1,13.80,21.00,55.9
HbA1c_level,6000.0,5.784583,0.956614,4.1,5.2,5.50,6.10,11.0
cholesterol_level,6000.0,217.490667,24.888595,139.0,200.0,217.00,234.00,309.0
triglycerides_level,6000.0,177.351500,51.897606,50.0,137.0,173.00,213.00,383.0
daily_calorie_intake,6000.0,2479.547000,548.410642,1200.0,2055.0,2385.00,2848.25,5249.0
sugar_intake_grams_per_day,6000.0,66.555733,39.576891,0.0,35.1,58.30,89.30,255.0
sleep_hours,6000.0,6.998700,1.331378,4.0,6.1,7.10,8.00,10.0
stress_level,6000.0,5.086500,2.342989,1.0,3.0,5.00,7.00,10.0
waist_circumference_cm,6000.0,105.049600,25.079335,60.0,84.7,104.60,124.20,150.0
diabetes_risk_score,6000.0,48.691417,37.242034,0.0,12.9,43.90,88.80,100.0

In [19]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
blood_pressure                0
fasting_glucose_level         0
insulin_level                 0
HbA1c_level                   0
cholesterol_level             0
triglycerides_level           0
physical_activity_level       0
daily_calorie_intake          0
sugar_intake_grams_per_day    0
sleep_hours                   0
stress_level                  0
family_history_diabetes       0
waist_circumference_cm        0
diabetes_risk_score           0
diabetes_risk_category        0
dtype: int64

In [20]:
target = "diabetes_risk_category"